version: 0.2
env:
  variables:
    APP_NAME: "kammryndancy"
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo install process started
      - if [ -z "${BRANCH}" ]; then echo "BRANCH not set" && exit 1 ; fi
      - if [ -z "${ENVIRONMENT}" ]; then echo "ENVIRONMENT not set" && exit 1 ; fi
      - npm install && npm install -g @angular/cl
    build:
      commands:
        - echo build process started now
        - git checkout $BRANCH
        - ng build --configuration=$ENVIRONMENT
      post_build:
        commands:
          - echo build process finished, uploading to S3
          - cd dist/$APP_NAME
          - ls -la
          - aws s3 sync . s3://kammryndancy.com/$ENVIRONMENT
